title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    fields:
      - name: name
        type: string
        example: "Click here"
      - name: url
        type: url
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
  ghost:
    title: "Ghost"
    description: |
      The ghost button is to draw attention for things such as a "call-to-action".
  light:
    fields:
      - name: name
        type: string
        example: "Click here"
      - name: url
        type: url
    title: "Light"
    description: |
      The light button is specifically for banners, where it will be placed in front of busy images.
  option:
    title: "Option"
    description: |
      The option button is for checkout and product options.
  search:
    title: "Search"
    description: |
      The search button is only to be paired with search bar and shouldn't be touched.
