title: "Headers"
description: |
  Header contains the website logo and often navigation links to navigate the site.

patterns:
  header-main:
    title: "Main Header"
    description: |
      This is the header thats to be used on almost all pages.
  header-no-nav:
    title: "No Navigation Header"
    description: |
      This is the header thats to be used only on checkout pages.
